name: Pull Request Template
description: Template for creating pull requests in this repository
body:
  - type: markdown
    attributes:
      value: |
        ## Pull Request Description
        Please provide a detailed description of your changes and why they are necessary.

  - type: input
    id: title
    attributes:
      label: Pull Request Title
      description: Provide a concise title for your pull request.
      placeholder: e.g., "Fix login form validation"
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the changes introduced in this pull request.
      placeholder: e.g., "This PR adds form validation to the login page to prevent incorrect data submission."
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure your pull request meets the following criteria.
      options:
        - label: "I have tested my changes locally and they work as expected."
        - label: "I have added or updated documentation as needed."
        - label: "I have reviewed the code for best practices and consistency."
        - label: "I have run linting and tests, and they pass successfully."

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any other information that might be relevant to this pull request.
      placeholder: e.g., "Known issues, future considerations, etc."
