name: Question
description: Ask a question about the project
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        ## Question
        Have a question? Use this template to get answers from the maintainers or community.

  - type: input
    id: title
    attributes:
      label: Title
      description: Provide a concise title for your question.
      placeholder: e.g., "How do I deploy the project?"
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe your question in detail.
      placeholder: e.g., "I'm not sure how to configure the project for deployment. Are there any guides?"
